import Link from "next/link";
import React from "react";

export const metadata = {
  title: "About Next App",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <h1>About Page</h1>
      <Link className=" text-blue-500 text-xl ml-10" href={"/"}>
        Home
      </Link>
    </div>
  );
};

export default AboutPage;
