import Link from "next/link";
import React from "react";
import LinkFile from "./LinkFile";

export const metadata = {
  title: "About Next App",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <h1>About Page</h1>
      <LinkFile />
    </div>
  );
};

export default AboutPage;
